cask_args appdir: '/Applications'
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/completions'
tap 'homebrew/versions'
brew 'bash-completion'
brew 'git'
cask 'atom'
cask 'google-chrome'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
